version: '3'
services: 
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    container_name: "server"
    command: "yarn server"
    environment: 
      NODE_ENV: "development"
      MONGO_USER: "kakapo"
      MONGO_PASSWORD: "nightparrot"
      MONGO_DB: "todo_trial"
    ports:
      - 3000:3000
    links: 
      - mongo
    depends_on: 
      - mongo
    volumes:
      - ./src/server:/app/src/server
      - ./server:/app/server
      - /app/node_modules
  mongo:
    image: mongo
    container_name: "mongo"
    command: "mongod"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kakapo
      MONGO_INITDB_ROOT_PASSWORD: nightparrot
      MONGO_INITDB_DATABASE: todo_trial
    volumes:
      - mongo-data:/data/db
  mongo-data:
    image: busybox
volumes: 
  mongo-data: