version: '3'
services: 
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    container_name: "server"
    command: "yarn server"
    environment: 
      NODE_ENV: "development"
      MONGO_USER: "kakapo"
      MONGO_PASSWORD: "nightparrot"
      MONGO_DB: "todo_trial"
    ports:
      - 3000:3000
    links: 
      - mongo
    depends_on: 
      - mongo
    volumes:
      - ./src/server:/app/src/server
      - ./server:/app/server
      - /app/node_modules
  mongo-express:
    image: mongo-express
    restart: always
    container_name: "mongo-express"
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kakapo
      ME_CONFIG_MONGODB_ADMINPASSWORD: nightparrot
  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    command: "mongod"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kakapo
      MONGO_INITDB_ROOT_PASSWORD: nightparrot
      MONGO_INITDB_DATABASE: todo_trial
      TZ: Asia/Tokyo
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
  mongo-data:
    image: busybox
volumes: 
  mongo-data: